"""Squashed baseline schema, with real DDL.

The original migration chain was unrunnable from a fresh clone: several
revisions (001, 007, 009, 011) were committed as empty stubs and later
deleted, leaving dangling down_revision references, and env.py was removed.
Both the dev quickstart and production actually built the schema from the
SQLAlchemy models via Base.metadata.create_all at startup, so alembic had
drifted into a broken, decorative state -- nothing ever ran `alembic upgrade
head` for real. A 2026-07-21 squash consolidated history into this revision,
but its upgrade() just called create_all() again rather than real DDL, and
the then-running production container was never rebuilt on a fresh image, so
it kept serving the old corrupted revision files (confirmed directly on the
live container: alembic_version was still stamped at the old, deleted
revision '012', and 9 of 13 baked-in migration files were 0 bytes).

This revision replaces the create_all()-based upgrade() with explicit,
reviewable DDL generated via `alembic revision --autogenerate` against an
empty database and the current models -- this is what "real Alembic" means:
inspectable migrations, not a lazy metadata call. downgrade() is now a real,
scoped reversal (drops exactly what upgrade() creates, in FK-safe order)
instead of a blanket Base.metadata.drop_all().

Production's live schema was independently audited and repaired to match
these models exactly before this revision was cut (missing enum value,
narrow varchar column, missing ON DELETE CASCADE on 5 foreign keys, and the
enum type's own misspelled name) -- see CHANGELOG.md 1.12.20 for specifics.
Production is stamped to this revision (no DDL re-run needed, checked
schema-identical via `alembic revision --autogenerate` producing an empty
diff) rather than migrated, since the schema already matches.

Revision ID: 0001_squashed_baseline
Revises:
Create Date: 2026-07-22

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_squashed_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('password_reset_token', sa.String(length=512), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('llm_ollama_url', sa.String(length=512), nullable=True),
    sa.Column('summary_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'cancelled', name='processingstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('video_file_path', sa.String(length=512), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('summarize_status', sa.String(length=20), nullable=True),
    sa.Column('slide_status', sa.String(length=20), nullable=True),
    sa.Column('processing_mode', sa.String(length=20), server_default='standard', nullable=True),
    sa.Column('caption_language', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_processing_jobs_created_at', 'processing_jobs', ['created_at'], unique=False)
    op.create_index('ix_processing_jobs_job_id', 'processing_jobs', ['job_id'], unique=False)
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'], unique=False)
    op.create_index('ix_processing_jobs_user_id', 'processing_jobs', ['user_id'], unique=False)
    op.create_index('ix_processing_jobs_user_id_created_at', 'processing_jobs', ['user_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_job_id_format', 'documents', ['job_id', 'format'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'error', name='loglevel'), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_job_id_created_at', 'job_logs', ['job_id', 'created_at'], unique=False)
    op.create_table('slide_detection_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('total_frames_sampled', sa.Integer(), nullable=True),
    sa.Column('sampling_fps', sa.Float(), nullable=True),
    sa.Column('ssim_threshold', sa.Float(), nullable=True),
    sa.Column('ssim_ambiguous_low', sa.Float(), nullable=True),
    sa.Column('ssim_ambiguous_high', sa.Float(), nullable=True),
    sa.Column('layout_type_detected', sa.String(length=50), nullable=True),
    sa.Column('total_slides', sa.Integer(), nullable=True),
    sa.Column('total_transitions', sa.Integer(), nullable=True),
    sa.Column('llm_classifications_count', sa.Integer(), nullable=True),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_slide_detection_metadata_job_id', 'slide_detection_metadata', ['job_id'], unique=False)
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=False),
    sa.Column('end_timestamp', sa.Float(), nullable=False),
    sa.Column('final_frame_path', sa.String(length=512), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('layout_type', sa.String(length=50), nullable=True),
    sa.Column('ssim_transition_score', sa.Float(), nullable=True),
    sa.Column('is_incremental_build', sa.Boolean(), nullable=False),
    sa.Column('parent_slide_id', sa.Integer(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_slide_id'], ['slides.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slides_job_id_slide_number', 'slides', ['job_id', 'slide_number'], unique=False)
    op.create_index('ix_slides_job_id_start_timestamp', 'slides', ['job_id', 'start_timestamp'], unique=False)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcripts_job_id', 'transcripts', ['job_id'], unique=False)
    op.create_index('ix_transcripts_language', 'transcripts', ['language'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('video_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'job_id', name='uq_videos_video_id_job_id')
    )
    op.create_index('ix_videos_created_at', 'videos', ['created_at'], unique=False)
    op.create_index('ix_videos_job_id', 'videos', ['job_id'], unique=False)
    op.create_index('ix_videos_video_id', 'videos', ['video_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('detected_text', sa.Text(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.Column('ssim_delta_vs_prev', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_job_id_timestamp', 'snapshots', ['job_id', 'timestamp'], unique=False)
    op.create_index('ix_snapshots_relevance_score', 'snapshots', ['relevance_score'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcript_segments_start_time', 'transcript_segments', ['start_time'], unique=False)
    op.create_index('ix_transcript_segments_transcript_id_sequence', 'transcript_segments', ['transcript_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transcript_segments_transcript_id_sequence', table_name='transcript_segments')
    op.drop_index('ix_transcript_segments_start_time', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index('ix_snapshots_relevance_score', table_name='snapshots')
    op.drop_index('ix_snapshots_job_id_timestamp', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index('ix_videos_video_id', table_name='videos')
    op.drop_index('ix_videos_job_id', table_name='videos')
    op.drop_index('ix_videos_created_at', table_name='videos')
    op.drop_table('videos')
    op.drop_index('ix_transcripts_language', table_name='transcripts')
    op.drop_index('ix_transcripts_job_id', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index('ix_slides_job_id_start_timestamp', table_name='slides')
    op.drop_index('ix_slides_job_id_slide_number', table_name='slides')
    op.drop_table('slides')
    op.drop_index('ix_slide_detection_metadata_job_id', table_name='slide_detection_metadata')
    op.drop_table('slide_detection_metadata')
    op.drop_index('ix_job_logs_job_id_created_at', table_name='job_logs')
    op.drop_table('job_logs')
    # Postgres doesn't auto-drop custom enum types when the last column
    # using them is dropped -- autogenerate misses this, so it's explicit
    # here (found by testing a real downgrade -> upgrade cycle, which the
    # original generated migration failed: "type already exists").
    sa.Enum(name='loglevel').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_documents_job_id_format', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_processing_jobs_user_id_created_at', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_user_id', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_status', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_job_id', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_created_at', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    sa.Enum(name='processingstatus').drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
